pip_version = "24.0"
obligated_requirements = ["setuptools>=68.0.0", "wheel>=0.38.0"]


# 获取CPython独立打包 https://github.com/indygreg/python-build-standalone/releases
[[cpython]]
python_version = "3.12"
version = "3.12.2+20240224"
url = "https://gitee.com/lyucg/python-dists/releases/download/20240224/cpython-3.12.2+20240224-x86_64-pc-windows-msvc-shared-install_only.tar.gz"
checksum = "1e5655a6ccb1a64a78460e4e3ee21036c70246800f176a6c91043a3fe3654a3b"

[[cpython]]
python_version = "3.8"
version = "3.8.18+20240224"
url = "https://gitee.com/lyucg/python-dists/releases/download/20240224/cpython-3.8.18+20240224-x86_64-pc-windows-msvc-shared-install_only.tar.gz"
checksum = "dba923ee5df8f99db04f599e826be92880746c02247c8d8e4d955d4bc711af11"

[[pypi]]
name = "清华镜像"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"

[[pypi]]
name = "阿里云镜像"
url = "http://mirrors.aliyun.com/pypi/simple"

[[pypi]]
name = "官方PyPI镜像"
url = "https://pypi.org/simple"
